package io.github.diet103.lector.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM backed by the Android Keystore (PLAN §5).
 *
 * The key material never leaves the TEE and cannot be exported, so the ciphertext is worthless on
 * any other device — which is the real reason a stolen backup can't yield the user's ElevenLabs
 * key, over and above the backup-exclusion rules.
 *
 * Layout is `[12-byte IV][ciphertext+16-byte GCM tag]`. The IV is generated by the Keystore per
 * encryption (randomised encryption is required and we never supply our own), so it has to travel
 * with the ciphertext.
 *
 * Every failure path returns `null` rather than throwing: a key invalidated by a lock-screen
 * change or a restored-from-backup blob is an expected state, and [ApiKeyStore] turns it into a
 * clean "sign in again" instead of a crash.
 */
class KeystoreAesGcmCipher(private val alias: String = DEFAULT_ALIAS) : AesGcmCipher {

    override fun encrypt(plaintext: String): ByteArray? = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val encrypted = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        cipher.iv + encrypted
    }.getOrNull()

    override fun decrypt(ciphertext: ByteArray): String? = runCatching {
        if (ciphertext.size <= IV_LENGTH) return null
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_LENGTH_BITS, ciphertext, 0, IV_LENGTH)
        )
        val plaintext = cipher.doFinal(ciphertext, IV_LENGTH, ciphertext.size - IV_LENGTH)
        String(plaintext, Charsets.UTF_8)
    }.getOrNull()

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private companion object {
        const val DEFAULT_ALIAS = "lector.apikey.v1"
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_LENGTH = 12
        const val TAG_LENGTH_BITS = 128
    }
}
